spring:
  application:
    name: peer1
  # profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone : http://localhost:8762/eureka/,http://localhost:8763/eureka/
