spring:
  application:
    name: peer3
 # profiles: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone : http://localhost:8762/eureka/,http://localhost:8761/eureka/
