server:
  port: 8080
spring:
  application:
    name: swagger
#配置eureka获取服务地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
  #配置Swagger相关信息
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
    # ${server.port}为该服务的端口号
    # http://localhost:8080/swagger-ui.html 访问的地址
